### ISSUE TITLE
USER STORY: Add Location Map and Opening Times.

### ISSUE THREAD

**Issue by NaifatSelina** [NaifatSelina/FridasEats#10]
As a **customer** I can **see the location of Fridas' Eats and times it opens** so that **I can plan ahead**

# Acceptance Criteria
- Acceptance Criteria 1: Map of where Fridas' Diary is, is on the homepage.
- Acceptance Criteria 2: A list of opening times is shown.

# Tasks
- [ ] Add Map to homepage.
- [ ] Add opening and closing times.
- [ ] Style opening times section to be cohesive.
