### ISSUE TITLE
USER STORY: Ability to See Previously Left Reviews.

### ISSUE THREAD

**Issue by NaifatSelina** [NaifatSelina/FridasEats#14]
As a **customer** I can **see reviews** so that **I can make a decision on whether to visit the restaurant with that in mind**

# Acceptance Criteria
- Acceptance Criteria 1: Reviews Section Clearly Added.
- Acceptance Criteria 2:
- Acceptance Criteria 3:

# Tasks
- [ ] Add a reviews section.
- [ ] Ensure each review is laid out cohesively.
- [ ] Style to be clear.
