### ISSUE TITLE
USER STORY: Ability to Accuire Information About Fridas' Eats.

### ISSUE THREAD

**Issue by NaifatSelina** [NaifatSelina/FridasEats#15]
As a **customer** I can **read information about the restaurant** so that **I know why I should visit**

# Acceptance Criteria
- Acceptance Criteria 1: Complete the Our Passion section of the homepage.
- Acceptance Criteria 2: Add photos.

# Tasks
- [ ] Use HTML and Bootstrap to set up section.
- [ ] Add further customisation through css.
- [ ] Add fade in/out effect on photos.
