### ISSUE TITLE
USER STORY: Update README.md file with mock write up content.

### ISSUE THREAD

**Issue by NaifatSelina** [NaifatSelina/FridasEats#5]
As a **developper** I can **insert readme content I've already written up** so that **begin to build up my README file**

# Acceptance Criteria
- Acceptance Criteria 1: Transfer all README write up content from device.
- Acceptance Criteria 2: Ensure syntax is correct.

# Tasks
- [ ] Update the README content with write up.
- [ ] Add Design Wireframe to README after compression.
- [ ] Add placeholder text for uncompleted section of README.
