### ISSUE TITLE
USER STORY: Create Main [Home] Webpage.

### ISSUE THREAD

**Issue by NaifatSelina** [NaifatSelina/FridasEats#6]
As a **user** I can **see and navigate the homepage** so that **it is clear that I am in the correct place**

# Acceptance Criteria
- Acceptance Criteria 1: Homepage is fully developed.
- Acceptance Criteria 2: Navigation Links work successfully.
- Acceptance Criteria 3: Colour and Fonts and appropriate and cohesive.

# Tasks
- [ ] Add Each Section to Homepage with HTML.
- [ ] Enhance each section with Bootstrap.
- [ ] Add further customisation with CSS.
